[package]
name = "goofi-graphics"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
goofi-core = { path = "../../goofi-core" }
goofi-node = { path = "../../goofi-node" }
goofi-codec = { path = "../../goofi-codec" }
goofi-transport = { path = "../../goofi-transport" }
goofi-control = { path = "../../goofi-control" }
wgpu = { version = "30", default-features = false, features = ["wgsl", "vulkan", "metal", "dx12", "std"] }
naga = { version = "30", features = ["wgsl-in"] }
pollster = "0.4"
half = "2"
