[workspace]
resolver = "2"
members = [
    "crates/goofi-core",
    "crates/goofi-codec",
    "crates/goofi-node",
    "crates/goofi-dsp",
    "crates/goofi-nodes",
    "crates/goofi-engine",
    "crates/goofi-bridge",
    "crates/goofi-cli",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT"
rust-version = "1.89"

[profile.release]
lto = "thin"
codegen-units = 1
