// GENERATED from backend/goofi-bridge/src/ops.rs — do not edit by hand.
// The manager's op registry is the only place an op name is declared: naming one that is
// not in it is a type error here and an `unknown op` refusal there. Regenerate by running
// `cargo test -p goofi-bridge`, which rewrites this file when it drifts.
export type OpName =
	| 'list_dir'
	| 'list_nodes'
	| 'rescan_nodes'
	| 'add_node'
	| 'remove_node'
	| 'restart_node'
	| 'add_link'
	| 'remove_link'
	| 'refresh_param'
	| 'set_param'
	| 'set_node_pos'
	| 'set_viewpoint'
	| 'inspect_layout'
	| 'add_tab'
	| 'remove_tab'
	| 'rename_tab'
	| 'reorder_tab'
	| 'split_panel'
	| 'set_panel'
	| 'move_panel'
	| 'insert_at_panel'
	| 'resize_split'
	| 'remove_panel'
	| 'set_node_viewers'
	| 'rename_node'
	| 'add_global'
	| 'set_global'
	| 'remove_global'
	| 'rename_global'
	| 'group_nodes'
	| 'expand_instance'
	| 'add_boundary'
	| 'wire_boundary'
	| 'remove_boundary'
	| 'rename_boundary'
	| 'set_boundary_pos'
	| 'serialize'
	| 'open_workspace'
	| 'save'
	| 'load_text'
	| 'load'
	| 'new'
	| 'undo'
	| 'redo'
	| 'inspect_patch'
	| 'inspect_node'
	| 'get_patch'
	| 'list_globals'
	| 'list_harnesses'
	| 'spawn_harness'
	| 'stop_harness'
	| 'read_node_source';
