// GENERATED from backend/goofi-bridge/src/ops.rs — do not edit by hand.
// The manager's op registry is the only place an op name is declared: naming one that is
// not in it is a type error here and an `unknown op` refusal there. Regenerate by running
// `cargo test -p goofi-bridge`, which rewrites this file when it drifts.
export type OpName =
	| 'list_dir'
	| 'list_nodes'
	| 'rescan_nodes'
	| 'add_node'
	| 'remove_node'
	| 'restart_node'
	| 'add_link'
	| 'remove_link'
	| 'refresh_param'
	| 'edit_node'
	| 'set_viewpoint'
	| 'inspect_layout'
	| 'edit_panel'
	| 'place_panel'
	| 'remove_panel'
	| 'set_global'
	| 'compound'
	| 'group_nodes'
	| 'expand_instance'
	| 'serialize'
	| 'save'
	| 'load'
	| 'undo'
	| 'redo'
	| 'inspect_patch'
	| 'inspect_node'
	| 'get_patch'
	| 'list_globals'
	| 'list_harnesses'
	| 'spawn_harness'
	| 'stop_harness';
