// GENERATED from backend/goofi-bridge/src/ops.rs — do not edit by hand.
// The manager's op registry is the only place an op name is declared: naming one that is
// not in it is a type error here and an `unknown op` refusal there. Regenerate by running
// `cargo test -p goofi-bridge`, which rewrites this file when it drifts.
export type OpName =
	| 'session status'
	| 'session state'
	| 'session manifest'
	| 'session save'
	| 'session load'
	| 'session new'
	| 'node state'
	| 'node add'
	| 'node edit'
	| 'node param edit'
	| 'node remove'
	| 'node restart'
	| 'node param refresh'
	| 'nodes inspect'
	| 'nodes copy'
	| 'nodes paste'
	| 'nodes group'
	| 'nodes ungroup'
	| 'link add'
	| 'link remove'
	| 'global list'
	| 'global add'
	| 'global edit'
	| 'global remove'
	| 'library list'
	| 'library get'
	| 'library refresh'
	| 'dir list'
	| 'op list'
	| 'agent list'
	| 'agent start'
	| 'agent stop'
	| 'undo'
	| 'redo'
	| 'compound'
	| 'layout inspect'
	| 'layout panel add'
	| 'layout move'
	| 'layout remove'
	| 'layout tab edit'
	| 'layout panel edit'
	| 'layout split edit'
	| 'layout viewpoint edit';
