/** The numpy names offered after `np.` — hand-picked, never the real namespace. */

const FUNCTIONS = [
	'abs',
	'angle',
	'arange',
	'arccos',
	'arcsin',
	'arctan',
	'arctan2',
	'argmax',
	'argmin',
	'argsort',
	'array',
	'asarray',
	'blackman',
	'ceil',
	'clip',
	'concatenate',
	'cos',
	'cosh',
	'cumsum',
	'degrees',
	'diff',
	'dot',
	'exp',
	'eye',
	'flip',
	'floor',
	'full',
	'hamming',
	'hanning',
	'hstack',
	'imag',
	'interp',
	'isfinite',
	'isnan',
	'linspace',
	'log',
	'log2',
	'log10',
	'max',
	'maximum',
	'mean',
	'median',
	'min',
	'minimum',
	'nanmean',
	'nanstd',
	'ones',
	'percentile',
	'power',
	'prod',
	'radians',
	'ravel',
	'real',
	'reshape',
	'roll',
	'round',
	'sign',
	'sin',
	'sinh',
	'sort',
	'sqrt',
	'square',
	'std',
	'sum',
	'tan',
	'tanh',
	'transpose',
	'unwrap',
	'var',
	'vstack',
	'where',
	'zeros'
];

const CONSTANTS = ['e', 'inf', 'nan', 'newaxis', 'pi'];

const NAMESPACES = ['fft', 'linalg', 'random'];

export const CURATED_NUMPY: { name: string; type: 'function' | 'constant' | 'namespace' }[] = [
	...FUNCTIONS.map((name) => ({ name, type: 'function' as const })),
	...CONSTANTS.map((name) => ({ name, type: 'constant' as const })),
	...NAMESPACES.map((name) => ({ name, type: 'namespace' as const }))
];
