//! Golden conformance: the Rust GOOF encoder must match the authoritative legacy
//! Python codec byte-for-byte on the deterministic parts (header magic/version/tag,
//! body) and semantically on the msgpack meta (order-independent). Fixtures are
//! generated by `tests/gen_golden.py` from the real `goofi.codec`.
//!
//! The case list below MIRRORS `gen_golden.py` exactly — the two must agree by
//! construction; that agreement is the contract this test enforces.

use std::collections::BTreeMap;

use goofi_codec::{encode, split_frame};
use goofi_core::{Axes, Axis, Coord, Data, DType, Meta};
use indexmap::IndexMap;

// ------- typed array builders -------

fn arr(dtype: DType, shape: &[usize], buf: Vec<u8>, meta: Meta) -> Data {
    Data::from_array_bytes(dtype, shape.to_vec(), buf, meta).unwrap()
}

fn f32s(vals: &[f32]) -> Vec<u8> {
    vals.iter().flat_map(|v| v.to_le_bytes()).collect()
}

fn build_cases() -> Vec<(&'static str, Data)> {
    let meta_sfreq_ch = Meta {
        sfreq: Some(250.0),
        channels: Axes::new().with(0, Axis::coords(vec![Coord::Str("Fz".into()), Coord::Str("Cz".into())])),
        ..Default::default()
    };
    let meta_index = Meta {
        index: Some(42),
        ..Default::default()
    };

    let mut table = IndexMap::new();
    table.insert("a".to_string(), arr(DType::F32, &[2], f32s(&[1.0, 2.0]), Meta::empty()));
    table.insert("b".to_string(), Data::string("x", Meta::empty()));

    vec![
        ("f32_1d", arr(DType::F32, &[3], f32s(&[1.0, 2.0, 3.0]), Meta::empty())),
        ("u8_2d", arr(DType::U8, &[2, 3], vec![1, 2, 3, 4, 5, 6], Meta::empty())),
        (
            "i16_1d",
            arr(
                DType::I16,
                &[3],
                [-1i16, 0, 32767].iter().flat_map(|v| v.to_le_bytes()).collect(),
                Meta::empty(),
            ),
        ),
        (
            "i32_3d",
            arr(
                DType::I32,
                &[2, 3, 4],
                (0i32..24).flat_map(|v| v.to_le_bytes()).collect(),
                Meta::empty(),
            ),
        ),
        (
            "u32_1d",
            arr(
                DType::U32,
                &[3],
                [0u32, 1, 4294967295].iter().flat_map(|v| v.to_le_bytes()).collect(),
                Meta::empty(),
            ),
        ),
        (
            "i64_1d",
            arr(
                DType::I64,
                &[3],
                [1i64, -2, 3].iter().flat_map(|v| v.to_le_bytes()).collect(),
                Meta::empty(),
            ),
        ),
        (
            "u64_1d",
            arr(
                DType::U64,
                &[3],
                [0u64, 1, u64::MAX].iter().flat_map(|v| v.to_le_bytes()).collect(),
                Meta::empty(),
            ),
        ),
        (
            "f64_narrow",
            arr(
                DType::F64,
                &[2],
                [1.5f64, 2.5].iter().flat_map(|v| v.to_le_bytes()).collect(),
                Meta::empty(),
            ),
        ),
        (
            "f16_1d",
            // IEEE-754 half: 1.0 = 0x3C00, 2.0 = 0x4000 (little-endian bytes)
            arr(DType::F16, &[2], vec![0x00, 0x3C, 0x00, 0x40], Meta::empty()),
        ),
        ("bool_1d", arr(DType::Bool, &[3], vec![1, 0, 1], Meta::empty())),
        // 0-d scalar promotes to shape (1,)
        ("scalar_0d", arr(DType::F32, &[], f32s(&[3.0]), Meta::empty())),
        ("empty_array", arr(DType::F32, &[0], vec![], Meta::empty())),
        (
            "with_sfreq_channels",
            arr(DType::F32, &[2, 3], f32s(&[0.0, 1.0, 2.0, 3.0, 4.0, 5.0]), meta_sfreq_ch),
        ),
        (
            "with_index",
            arr(DType::F32, &[4], f32s(&[1.0, 2.0, 3.0, 4.0]), meta_index),
        ),
        ("string", Data::string("hello world éà", Meta::empty())),
        ("string_empty", Data::string("", Meta::empty())),
        ("table", Data::table(table, Meta::empty())),
        ("table_empty", Data::table(IndexMap::new(), Meta::empty())),
    ]
}

// ------- semantic msgpack comparison (order-independent) -------

#[derive(PartialEq, Debug)]
enum Canon {
    Nil,
    Bool(bool),
    Int(i128),
    F(u64),
    Str(String),
    Bytes(Vec<u8>),
    Arr(Vec<Canon>),
    Map(BTreeMap<String, Canon>),
}

fn canon(v: &rmpv::Value) -> Canon {
    use rmpv::Value::*;
    match v {
        Nil => Canon::Nil,
        Boolean(b) => Canon::Bool(*b),
        Integer(i) => Canon::Int(
            i.as_i64()
                .map(|x| x as i128)
                .or_else(|| i.as_u64().map(|x| x as i128))
                .expect("integer fits"),
        ),
        F32(f) => Canon::F((*f as f64).to_bits()),
        F64(f) => Canon::F(f.to_bits()),
        String(s) => Canon::Str(s.as_str().unwrap_or_default().to_string()),
        Binary(b) => Canon::Bytes(b.clone()),
        Array(a) => Canon::Arr(a.iter().map(canon).collect()),
        Map(m) => Canon::Map(
            m.iter()
                .map(|(k, v)| (k.as_str().unwrap().to_string(), canon(v)))
                .collect(),
        ),
        Ext(_, _) => panic!("unexpected msgpack ext in meta"),
    }
}

fn decode_meta(bytes: &[u8]) -> rmpv::Value {
    let mut rd = bytes;
    rmpv::decode::read_value(&mut rd).expect("decode meta msgpack")
}

fn load_fixture() -> serde_json::Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/goof_golden.json");
    let text = std::fs::read_to_string(path).expect("read fixture (run gen_golden.py)");
    serde_json::from_str(&text).expect("parse fixture json")
}

#[test]
fn goof_encoder_matches_python_golden() {
    let fixture = load_fixture();
    let cases_json = fixture.get("cases").expect("cases key");
    let native = build_cases();

    // Every Python case must be covered by a Rust case (no silent gaps).
    let py_names: Vec<&str> = cases_json.as_object().unwrap().keys().map(|s| s.as_str()).collect();
    for name in &py_names {
        assert!(
            native.iter().any(|(n, _)| n == name),
            "Python golden case `{name}` has no matching Rust case"
        );
    }
    assert_eq!(native.len(), py_names.len(), "case count mismatch Rust vs Python");

    for (name, data) in &native {
        let py_frame: Vec<u8> = cases_json[name]["frame"]
            .as_array()
            .unwrap()
            .iter()
            .map(|n| n.as_u64().unwrap() as u8)
            .collect();

        let rust_frame = encode(data);

        let (rt_tag, rt_meta, rt_body) = split_frame(&rust_frame).expect("rust frame valid");
        let (py_tag, py_meta, py_body) = split_frame(&py_frame).expect("py frame valid");

        assert_eq!(rt_tag, py_tag, "[{name}] dtype tag");
        assert_eq!(rt_body, py_body, "[{name}] body bytes must be byte-identical");
        assert_eq!(
            canon(&decode_meta(rt_meta)),
            canon(&decode_meta(py_meta)),
            "[{name}] meta must be semantically equal"
        );
    }
}
